### ISSUE TITLE
失效了？

### ISSUE THREAD

**Issue by redapple0204** [lizongzeshunshun/public#1]

**Comment by lizongzeshunshun** [comment]
如果能注册应该就可以

**Comment by redapple0204** [comment]
不过似乎不行，原有的账号能用？

**Comment by lizongzeshunshun** [comment]
那就不行了

**Comment by redapple0204** [comment]
欸等等，还是可以通过github登陆的
![18](https://cloud.githubusercontent.com/assets/16254644/23329896/f2e0eea0-fb7c-11e6-9740-f962df35243e.PNG)
